version: '3.8'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000

  drinktionary:
    image: drinktionary:latest
    expose:
      - "8081"

  auth:
    image: auth:latest
    expose:
      - "8090"

#  sentimentAnalysis:
#    image: sentimentanalysis:latest
#    expose:
#      - "8091"