version: '3.8'

services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    networks:
      - eureka-network

networks:
  eureka-network:
    driver: bridge