server:
  port: 9000

spring:
  application:
    name: gateway
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  profiles:
    include: jwt
  cloud:
    config:
        enabled: false

    gateway:
      routes:
        - id: auth
          uri: http://13.124.194.48:8090/
          predicates:
                - Path=/auth/**
        - id: analyze
          uri: http://13.124.194.48:8095/
          predicates:
            - Path=/analyze/**
          filters:
            - name: AuthorizationHeaderFilter
        - id: drinktionary
          uri: http://13.124.194.48:8091/
          predicates:
            - Path=/drinks/**
          filters:
            - name: AuthorizationHeaderFilter

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://13.124.194.48:8761/eureka/

